// <auto-generated />
using System;
using Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entity.Migrations.Loan
{
    [DbContext(typeof(LoanContext))]
    partial class LoanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Entity.Lender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lenders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Entity.Entity.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Amount");

                    b.Property<bool>("IsPaid");

                    b.Property<int>("LenderId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LenderId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000f,
                            IsPaid = false,
                            LenderId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Amount = 300f,
                            IsPaid = false,
                            LenderId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Amount = 300f,
                            IsPaid = false,
                            LenderId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2300f,
                            IsPaid = false,
                            LenderId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First_Name");

                    b.Property<string>("Last_Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            First_Name = "Adam",
                            Last_Name = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            First_Name = "Wojtek",
                            Last_Name = "Wilk"
                        },
                        new
                        {
                            Id = 3,
                            First_Name = "Anna",
                            Last_Name = "Gesler"
                        },
                        new
                        {
                            Id = 4,
                            First_Name = "Anna",
                            Last_Name = "Malynowska"
                        },
                        new
                        {
                            Id = 5,
                            First_Name = "Anna",
                            Last_Name = "Szczeciniak"
                        });
                });

            modelBuilder.Entity("Entity.Entity.Lender", b =>
                {
                    b.HasOne("Entity.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entity.Entity.Loan", b =>
                {
                    b.HasOne("Entity.Entity.Lender", "Lender")
                        .WithMany()
                        .HasForeignKey("LenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entity.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
